require "faker"

User.create(
  first_name: "Tony", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "man", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "woman", 
  email: "tony@avengers.com", 
  url1: "https://www.pinkvilla.com/imageresize/Avengers%20Endgame%20toy%20leak%20REVEALS%20Tony%20Stark%20aka%20Iron%20Man%27s%20new%20suit%20%281%29.jpg?width=752&format=webp&t=pvorg", 
  about: "My armor, it was never a distraction or a hobby, it was a cocoon. And now, I'm a changed man. You can take away my house, all my tricks and toys. But one thing you can't take away... I am Iron Man.",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Peter", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "man", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "woman", 
  email: "peter@avengers.com", 
  url1: "https://i.insider.com/5f778d302400440019129c6a?width=700", 
  about: "I'd rather just stay on the ground for a little while. Friendly neighborhood Spider-Man. Somebody's got to look out for the little guy, right?",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Michelle", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "woman", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "man", 
  email: "michelle@avengers.com", 
  url1: "https://i.pinimg.com/736x/15/6c/67/156c67d09331c4e1ab7e795bee5ec483.jpg", 
  about: "I love people. I love them so much.",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Steve", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "man", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "woman", 
  email: "steve@avengers.com", 
  url1: "https://firewireblog.com/wp-content/uploads/2021/01/tumblr_n0oxpj88rs1raoayro1_1280.jpg", 
  about: "Compromise where you can. Where you can't, don't. Even if everyone is telling you that something wrong is something right. Even if the whole world is telling you to move, it is your duty to plant yourself like a tree, look them in the eye, and say, 'No, you move.'",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Natasha", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "woman", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "man", 
  email: "natasha@avengers.com", 
  url1: "https://img.wallpapersafari.com/tablet/768/1024/88/38/dJTu4M.jpg", 
  about: "Yes, the world is a vulnerable place, and yes, we helped make it that way. But we’re also the ones best qualified to defend it. So if you want to arrest me, arrest me. You’ll know where to find me.",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Bruce", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "man", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "woman", 
  email: "bruce@avengers.com", 
  url1: "https://i.redd.it/6nijkugx4h081.jpg", 
  about: "For years, I've been treating the Hulk like he's some kind of disease, something to get rid of. But then I start looking at him as the cure. Eighteen months in the gamma lab, I put the brains and the brawn together and now look at me. Best of both worlds.",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Thor", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "man", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "woman", 
  email: "thor@avengers.com", 
  url1: "https://comicvine.gamespot.com/a/uploads/original/11133/111331200/6384517-thor%20image%20-%20copy.png", 
  about: "This drink, I like it! ANOTHER!",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Pepper", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "woman", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "man", 
  email: "pepper@avengers.com", 
  url1: "https://s3.r29static.com/bin/entry/9d3/0,200,2000,2000/x,80/2174391/image.jpg", 
  about: "I Think I Understand Why You Don't Want To Give Up The Suits. What Have I Got To Complain About Now?",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Wanda", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "woman", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "man", 
  email: "wanda@avengers.com", 
  url1: "https://assets.teenvogue.com/photos/5ba25a6336e1cd3772345a74/master/w_2800,h_4200,c_limit/lede.jpg", 
  about: "You Break The Rules And Become A Hero. I Do It And I Become The Enemy. That Hardly Seems Fair.",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Jane", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "woman", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "man", 
  email: "jane@avengers.com", 
  url1: "https://images6.fanpop.com/image/polls/1414000/1414000_1409762139722_full.jpg", 
  about: "I don't want it! I won't be a goddess! I won't stay in Asgard! It's too horrible! Too unendurable! Don't you realize how mad it is?!!",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Stephen", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "man", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "woman", 
  email: "stephen@avengers.com", 
  url1: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F6%2F2015%2F12%2Fdoctor-is-in-ew-008.jpg", 
  about: "If I Tell you What Happens, It Won't Happen.",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Carol", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "woman", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "man", 
  email: "carol@avengers.com", 
  url1: "https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_FMjpg_UX1000_.jpg", 
  about: "I’ve been fighting with one arm tied behind my back, but what happens when I’m finally set free?",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "T'Challa", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "man", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "woman", 
  email: "tchalla@avengers.com", 
  url1: "https://cdn.britannica.com/26/182826-050-0FEF618D/publicity-poster-Black-Panther-character-Tchalla-Black-Ryan-2017.jpg", 
  about: "In times of crisis, the wise build bridges while the foolish build barriers.",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Janet", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "woman", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "man", 
  email: "janet@avengers.com", 
  url1: "https://christyscozycorners.com/wp-content/uploads/2018/06/AntManAndTheWaspHope-1-691x1024.jpg", 
  about: "When you're small, energy's compressed, so you have the force of a 200-pound man behind a fist a 100th of an inch wide. You're like a bullet. You punch too hard, you kill someone. Too soft, it's a love tap. In other words, you have to know how to punch.",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Peggy", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "woman", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "man", 
  email: "peggy@avengers.com", 
  url1: "https://i.pinimg.com/originals/a0/46/1b/a0461b90ab54185717b438b2da3a6284.jpg", 
  about: "You have no idea how to talk to a woman, do you?",
  password: "123456",   
  password_confirmation: "123456")

User.create(
  first_name: "Scott", 
  dob_day: Faker::Number.within(range: 1..30), 
  dob_month: Faker::Number.within(range: 1..12), 
  dob_year: Faker::Number.within(range: 1980..2000), 
  show_gender: Faker::Boolean.boolean, 
  gender_identity: "man", 
  show_sexual_orientation: Faker::Boolean.boolean,
  sexual_orientation: "straight",
  gender_interest: "woman", 
  email: "scott@avengers.com", 
  url1: "https://assets.mycast.io/characters/scott-lang-241399-normal.jpg", 
  about: "Wait! I didn't steal anything! I was returning something I stole!",
  password: "123456",   
  password_confirmation: "123456")